openapi: 3.0.1
info:
  title: Orphadata API
  description: Provide API to Orphadata
  termsOfService: https://www.orpha.net/consor/cgi-bin/Education_AboutOrphanet.php?lng=EN
  contact:
    name: maintainer
    email: cyril.bigot@inserm.fr
  license:
    name: CC-BY-NC-SA
    url: https://creativecommons.org/licenses/by-nc-sa/3.0/fr/
  version: 1.0.0
externalDocs:
  description: For further information, checks Orphadata main site
  url: http://www.orphadata.org/cgi-bin/index.php
servers:
- url: /
  description: URL for Orphadata's API server
security:
- UserSecurity: []
- AdminSecurity: []
tags:
- name: clinical entity
  description: Full list of API operation for clinical entities
  externalDocs:
    description: Disorder or Disease object according to Orphanet Ontology
    url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2991&viewMode=All&siblings=false
- name: product1
  description: Operations for product 1
  externalDocs:
    description: Disorder or Disease object according to Orphanet Ontology
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: orphaclassif
  description: Hierarchical classification, Product 3
  externalDocs:
    description: Orphanet's hierarchical classification of clinical entities
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: phenotype
  description: Operations for phenotype, Product 4
  externalDocs:
    description: Phenotypes referenced by Orphanet, Human Phenotype Ontology (HPO)
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: clinical entity associated gene
  description: Operations for clinical entity associated genes, Product 6
  externalDocs:
    description: Genes referenced by Orphanet
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: gene
  description: Full list of API operation for genes, Product 6
  externalDocs:
    description: Gene referenced by Orphanet
    url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16612
- name: epidemiology
  description: Operations for epidemiology, Product 9
  externalDocs:
    description: Epidemiological data referenced by Orphanet
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
paths:
  /product1/language/{language}:
    get:
      tags:
      - clinical entity
      - product1
      summary: Get all product 1 in selected language
      description: Get the list of all clinical entity referenced in product 1 for
        the selected language
      operationId: product1_all_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product1_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /product1/list_orphacode/language/{language}:
    get:
      tags:
      - clinical entity
      - product1
      summary: List ORPHAcode for product 1 in selected language
      description: Get the list of ORPHAcode usable to query product 1 in selected
        language
      operationId: product1_list_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /product1/orphacode/{orphacode}/language/{language}:
    get:
      tags:
      - clinical entity
      - product1
      summary: clinical entity by ORPHAcode for product 1
      description: Access every information related to a clinical entity object by
        its ORPHAcode
      operationId: product1_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product1'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /orphaclassif/list_hchid:
    get:
      tags:
      - clinical entity
      - orphaclassif
      summary: List hierarchical ID (hchid)
      description: Get the list of hierarchical ID (hchid) usable to select an Orphanet's
        classification
      operationId: hierarchy_list_hchid
      parameters:
      - name: hchid
        in: path
        description: The hierarchy ID (hchID) is a number which refers to an Orphanet
          classification
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_hchid'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /orphaclassif/list_orphacode/hchid/{hchid}:
    get:
      tags:
      - clinical entity
      - orphaclassif
      summary: List ORPHAcode for selected classification
      description: Get the list of ORPHAcode usable to query the selected classification
      operationId: hierarchy_list_orphacode
      parameters:
      - name: hchid
        in: path
        description: The hierarchy ID (hchID) is a number which refers to an Orphanet
          classification
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /orphaclassif/hchid/{hchid}:
    get:
      tags:
      - clinical entity
      - orphaclassif
      summary: Get the full selected classification
      description: Get the list of all clinical entity referenced in orphaclassif
        for the selected classification
      operationId: hierarchy_all_orphacode
      parameters:
      - name: hchid
        in: path
        description: The hierarchy ID (hchID) is a number which refers to an Orphanet
          classification
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product3_classification_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /orphaclassif/orphacode/{orphacode}:
    get:
      tags:
      - clinical entity
      - orphaclassif
      summary: Hierarchical classification of clinical entities by ORPHAcode in all
        classifications
      description: Query one clinical entity by its ORPHAcode and gives the list of
        occurences in Orphanet's classifications with parents and childs clinical
        entity ORPHAcode number, the list of its children and parents.
      operationId: hierarchy_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product3_classification_list'
        "403":
          description: Access denied
        "404":
          description: Queried clinical entity not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /orphaclassif/orphacode/{orphacode}/hchid/{hchid}:
    get:
      tags:
      - clinical entity
      - orphaclassif
      summary: Hierarchical classification of clinical entities by ORPHAcode in selected
        classification
      description: Query one clinical entity by its ORPHAcode and gives the list of
        parents and childs clinical entity in the selected Orphanet's classification
      operationId: hierarchy_id_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: hchid
        in: path
        description: The hierarchy ID (hchID) is a number which refers to an Orphanet
          classification
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product3'
        "403":
          description: Access denied
        "404":
          description: Queried clinical entity not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /phenotype/language/{language}:
    get:
      tags:
      - clinical entity
      - phenotype
      summary: Get all phenotype in selected language
      description: Get the list of all clinical entity referenced in phenotype for
        the selected language
      operationId: phenotype_all_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product4_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /phenotype/list_orphacode/language/{language}:
    get:
      tags:
      - clinical entity
      - phenotype
      summary: List ORPHAcode for phenotype in selected language
      description: Get the list of ORPHAcode usable to query phenotype in selected
        language
      operationId: phenotype_list_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /phenotype/orphacode/{orphacode}/language/{language}:
    get:
      tags:
      - clinical entity
      - phenotype
      summary: Disorder by ORPHAcode with its associated phenotype
      description: Access every information related to a clinical entity by its ORPHAcode
      operationId: phenotype_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product4'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /associatedgene:
    get:
      tags:
      - clinical entity
      - clinical entity associated gene
      summary: Get all associatedgene
      description: Get the list of all clinical entity referenced in associatedgene
      operationId: associatedgene_all_orphacode
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product6_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /associatedgene/list_orphacode:
    get:
      tags:
      - clinical entity
      - clinical entity associated gene
      summary: List ORPHAcode for clinical entity associated gene
      description: Get the list of ORPHAcode usable to query clinical entity associated
        gene in selected language
      operationId: associatedgene_list_orphacode
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /associatedgene/orphacode/{orphacode}:
    get:
      tags:
      - clinical entity
      - clinical entity associated gene
      summary: Disorder by ORPHAcode with associated genes
      description: Access every information related to a clinical entity by its ORPHAcode
      operationId: associatedgene_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product6'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /gene:
    get:
      tags:
      - gene
      summary: Get all genes
      description: Get the list of all clinical entity referenced in gene
      operationId: gene_all_symbol
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product6_gene_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.gene_controller
  /gene/list_symbol:
    get:
      tags:
      - gene
      summary: List gene symbol to query by gene
      description: Get the list of gene symbol usable to query by gene
      operationId: gene_list_symbol
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_symbol'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.gene_controller
  /gene/symbol/{symbol}:
    get:
      tags:
      - gene
      summary: Gene by gene symbol with associated rare disorder
      description: Access every information related to a gene by its symbol
      operationId: gene_by_symbolv
      parameters:
      - name: symbol
        in: path
        description: The symbol is an identifier to reference a gene
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product6_gene'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.gene_controller
  /epidemiology/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: Get all epidemiology in selected language
      description: Get the list of all clinical entity referenced in epidemiology
        for the selected language
      operationId: epidemiology_all_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product9_prev_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /epidemiology/list_orphacode/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: List ORPHAcode for epidemiology in selected language
      description: Get the list of ORPHAcode usable to query epidemiology in selected
        language
      operationId: epidemiology_list_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /epidemiology/orphacode/{orphacode}/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: Disorder by ORPHAcode with epidemiological data
      description: Access every information related to a clinical entity by its ORPHAcode
      operationId: epidemiology_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product9_prev'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /natural_history/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: Get all natural_history in selected language
      description: Get the list of all clinical entity referenced in natural_history
        for the selected language
      operationId: natural_history_all_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product9_ages_list'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /natural_history/list_orphacode/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: List ORPHAcode for natural history in selected language
      description: Get the list of ORPHAcode usable to query natural history of clinical
        entity in selected language
      operationId: natural_history_list_orphacode
      parameters:
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_orphacode'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
  /natural_history/orphacode/{orphacode}/language/{language}:
    get:
      tags:
      - clinical entity
      - epidemiology
      summary: Disorder by ORPHAcode with age of onset
      description: Access every information related to a clinical entity by its ORPHAcode
      operationId: natural_history_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (CS, DE,
          EN, ES, FR, IT, NL, PL, PT)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - CS
          - DE
          - EN
          - ES
          - FR
          - IT
          - NL
          - PL
          - PT
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product9_ages'
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.clinical_entity_controller
components:
  schemas:
    product1_list:
      type: array
      items:
        $ref: '#/components/schemas/product1'
    product1:
      required:
      - ORPHAcode
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "166100"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166100
        Name:
          type: string
          example: Autosomal dominant otospondylomegaepiphyseal dysplasia
        DisorderFlag:
          type: array
          items:
            $ref: '#/components/schemas/product1_DisorderFlag'
        Synonym:
          type: array
          items:
            type: string
            example: '[''AD OSMED'', ''Stickler syndrome type 3'', ''Stickler syndrome,
              non-ocular type'']'
        DisorderType:
          $ref: '#/components/schemas/product1_DisorderType'
        DisorderNature:
          type: string
          example: Clinical entity
        DisorderGroup:
          type: string
          example: Disorder
        ExternalReference:
          type: array
          items:
            $ref: '#/components/schemas/product1_ExternalReference'
        DisorderDisorderAssociation:
          type: array
          items:
            $ref: '#/components/schemas/product1_DisorderDisorderAssociation'
        TextualInformation:
          type: array
          items:
            $ref: '#/components/schemas/product1_TextualInformation'
      example:
        DisorderFlag:
        - Label: on-line
        - Label: on-line
        ORPHAcode: "166100"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166100
        ExternalReference:
        - DisorderMappingICDRelation: None
          Reference: C537494
          DisorderMappingValidationStatus:
            ORPHAcode: "377819"
            Name: Validated
          Source: MeSH
          DisorderMappingRelation:
            ORPHAcode: "377807"
            Name: E (exact mapping (the terms and the concepts are equivalent))
        - DisorderMappingICDRelation: None
          Reference: C537494
          DisorderMappingValidationStatus:
            ORPHAcode: "377819"
            Name: Validated
          Source: MeSH
          DisorderMappingRelation:
            ORPHAcode: "377807"
            Name: E (exact mapping (the terms and the concepts are equivalent))
        DisorderDisorderAssociation:
        - DisorderDisorderAssociationType: Moved to
          Disorder1: None
          Disorder2:
            ORPHAcode: "3450"
            Name: Weissenbacher-Zweymuller syndrome
        - DisorderDisorderAssociationType: Moved to
          Disorder1: None
          Disorder2:
            ORPHAcode: "3450"
            Name: Weissenbacher-Zweymuller syndrome
        DisorderNature: Clinical entity
        DisorderGroup: Disorder
        Synonym:
        - '[''AD OSMED'', ''Stickler syndrome type 3'', ''Stickler syndrome, non-ocular
          type'']'
        - '[''AD OSMED'', ''Stickler syndrome type 3'', ''Stickler syndrome, non-ocular
          type'']'
        TextualInformation:
        - Definition: Stickler syndrome type 3 is a rare, genetic, multiple congenital
            anomalies/dysmorphic syndrome characterized by craniofacial dysmorphism
            (midface hypoplasia, depressed nasal bridge, small nose with upturned
            tip, cleft palate, Pierre Robin sequence), bilateral, pronounced sensorineural
            hearing loss, and skeletal/joint anomalies (including spondyloepiphyseal
            dysplasia, arthralgia/arthropathy), in the absence of ocular abnormalities.
        - Definition: Stickler syndrome type 3 is a rare, genetic, multiple congenital
            anomalies/dysmorphic syndrome characterized by craniofacial dysmorphism
            (midface hypoplasia, depressed nasal bridge, small nose with upturned
            tip, cleft palate, Pierre Robin sequence), bilateral, pronounced sensorineural
            hearing loss, and skeletal/joint anomalies (including spondyloepiphyseal
            dysplasia, arthralgia/arthropathy), in the absence of ocular abnormalities.
        DisorderType:
          ORPHAcode: "377789"
          Name: Malformation syndrome
        Name: Autosomal dominant otospondylomegaepiphyseal dysplasia
    product3_classification_list:
      type: array
      items:
        $ref: '#/components/schemas/product3'
    product3:
      required:
      - ORPHAcode
      type: object
      properties:
        name:
          type: string
          example: Familial isolated arrhythmogenic right ventricular dysplasia
        ORPHAcode:
          type: string
          example: "217656"
        hch_id:
          type: string
          example: "146"
        hch_tag:
          type: string
          example: Orphanet classification of rare cardiac diseases
        parents:
          type: array
          items:
            type: string
            example: '[''247'']'
        childs:
          type: array
          items:
            type: string
            example: '[''293888'', ''293899'', ''293910'']'
      example:
        ORPHAcode: "217656"
        hch_id: "146"
        hch_tag: Orphanet classification of rare cardiac diseases
        name: Familial isolated arrhythmogenic right ventricular dysplasia
        childs:
        - '[''293888'', ''293899'', ''293910'']'
        - '[''293888'', ''293899'', ''293910'']'
        parents:
        - '[''247'']'
        - '[''247'']'
    product4_list:
      type: array
      items:
        $ref: '#/components/schemas/product4'
    product4:
      type: object
      properties:
        Disorder:
          $ref: '#/components/schemas/product4_Disorder'
        Source:
          type: string
          example: 28705803[PMID]_17047017[PMID]_22707402[PMID]_25517026[PMID]_25438673[PMID]
        ValidationStatus:
          type: string
          example: "y"
        Online:
          type: string
          example: "y"
        ValidationDate:
          type: string
          example: 2016-10-19 00:00:00.0
      example:
        ValidationStatus: "y"
        ValidationDate: 2016-10-19 00:00:00.0
        Online: "y"
        Disorder:
          ORPHAcode: "881"
          ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=881
          DisorderGroup: Disorder
          HPODisorderAssociation:
          - HPO:
              HPOTerm: Abnormality of the ovary
              HPOId: HP:0000137
            HPOFrequency: Very frequent (99-80%)
            DiagnosticCriteria: None
          - HPO:
              HPOTerm: Abnormality of the ovary
              HPOId: HP:0000137
            HPOFrequency: Very frequent (99-80%)
            DiagnosticCriteria: None
          DisorderType: Malformation syndrome
          Name: Turner syndrome
        Source: 28705803[PMID]_17047017[PMID]_22707402[PMID]_25517026[PMID]_25438673[PMID]
    product6_list:
      type: array
      items:
        $ref: '#/components/schemas/product6'
    product6:
      required:
      - ORPHAcode
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "166024"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        Name:
          type: string
          example: Multiple epiphyseal dysplasia, Al-Gazali type
        DisorderType:
          type: string
          example: Disease
        DisorderGroup:
          type: string
          example: Disorder
        DisorderGeneAssociation:
          type: array
          items:
            $ref: '#/components/schemas/product6_DisorderGeneAssociation'
      example:
        DisorderGeneAssociation:
        - DisorderGeneAssociationStatus: Assessed
          Gene:
            ExternalReference:
            - Reference: ENSG00000166813
              Source: Ensembl
            - Reference: ENSG00000166813
              Source: Ensembl
            Symbol: KIF7
            Synonym:
            - '[''JBTS12'']'
            - '[''JBTS12'']'
            GeneType: gene with protein product
            Locus:
            - GeneLocus: 15q26.1
              LocusKey: "1"
            - GeneLocus: 15q26.1
              LocusKey: "1"
            Name: kinesin family member 7
          DisorderGeneAssociationType: Disease-causing germline mutation(s) in
          SourceOfValidation: 22587682[PMID]
        - DisorderGeneAssociationStatus: Assessed
          Gene:
            ExternalReference:
            - Reference: ENSG00000166813
              Source: Ensembl
            - Reference: ENSG00000166813
              Source: Ensembl
            Symbol: KIF7
            Synonym:
            - '[''JBTS12'']'
            - '[''JBTS12'']'
            GeneType: gene with protein product
            Locus:
            - GeneLocus: 15q26.1
              LocusKey: "1"
            - GeneLocus: 15q26.1
              LocusKey: "1"
            Name: kinesin family member 7
          DisorderGeneAssociationType: Disease-causing germline mutation(s) in
          SourceOfValidation: 22587682[PMID]
        ORPHAcode: "166024"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        DisorderGroup: Disorder
        DisorderType: Disease
        Name: Multiple epiphyseal dysplasia, Al-Gazali type
    product6_gene_list:
      type: array
      items:
        $ref: '#/components/schemas/product6_gene'
    product6_gene:
      required:
      - Symbol
      type: object
      properties:
        Name:
          type: string
          example: kinesin family member 7
        Symbol:
          type: string
          example: KIF7
        Synonym:
          type: array
          items:
            type: string
            example: '[''JBTS12'']'
        GeneType:
          type: string
          example: gene with protein product
        ExternalReference:
          type: array
          items:
            $ref: '#/components/schemas/product6_Gene_ExternalReference'
        Locus:
          type: array
          items:
            $ref: '#/components/schemas/product6_Gene_Locus'
        GeneDisorderAssociation:
          type: array
          items:
            $ref: '#/components/schemas/product6_gene_GeneDisorderAssociation'
      example:
        ExternalReference:
        - Reference: ENSG00000166813
          Source: Ensembl
        - Reference: ENSG00000166813
          Source: Ensembl
        Symbol: KIF7
        GeneDisorderAssociation:
        - DisorderGeneAssociationStatus: Assessed
          disorder:
            ORPHAcode: "166024"
            ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
            DisorderGroup: Disorder
            DisorderType: Disease
            Name: Multiple epiphyseal dysplasia, Al-Gazali type
          DisorderGeneAssociationType: Disease-causing germline mutation(s) in
          SourceOfValidation: 22587682[PMID]
        - DisorderGeneAssociationStatus: Assessed
          disorder:
            ORPHAcode: "166024"
            ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
            DisorderGroup: Disorder
            DisorderType: Disease
            Name: Multiple epiphyseal dysplasia, Al-Gazali type
          DisorderGeneAssociationType: Disease-causing germline mutation(s) in
          SourceOfValidation: 22587682[PMID]
        Synonym:
        - '[''JBTS12'']'
        - '[''JBTS12'']'
        GeneType: gene with protein product
        Locus:
        - GeneLocus: 15q26.1
          LocusKey: "1"
        - GeneLocus: 15q26.1
          LocusKey: "1"
        Name: kinesin family member 7
    product9_ages_list:
      type: array
      items:
        $ref: '#/components/schemas/product9_ages'
    product9_ages:
      required:
      - ORPHAcode
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "58"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=58
        Name:
          type: string
          example: Alexander disease
        DisorderType:
          type: string
          example: Disease
        DisorderGroup:
          type: string
          example: Disorder
        AverageAgeOfOnset:
          type: array
          items:
            type: string
            example: '[''All ages'']'
        AverageAgeOfDeath:
          type: array
          items:
            type: string
            example: '[''any age'']'
        TypeOfInheritance:
          type: array
          items:
            type: string
            example: '[''Autosomal dominant'']'
      example:
        AverageAgeOfOnset:
        - '[''All ages'']'
        - '[''All ages'']'
        AverageAgeOfDeath:
        - '[''any age'']'
        - '[''any age'']'
        ORPHAcode: "58"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=58
        DisorderGroup: Disorder
        TypeOfInheritance:
        - '[''Autosomal dominant'']'
        - '[''Autosomal dominant'']'
        DisorderType: Disease
        Name: Alexander disease
    product9_prev_list:
      type: array
      items:
        $ref: '#/components/schemas/product9_prev'
    product9_prev:
      required:
      - ORPHAcode
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "166024"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        Name:
          type: string
          example: Multiple epiphyseal dysplasia, Al-Gazali type
        DisorderType:
          type: string
          example: Disease
        DisorderGroup:
          type: string
          example: Disorder
        Prevalence:
          type: array
          items:
            $ref: '#/components/schemas/product9_prev_Prevalence'
      example:
        ORPHAcode: "166024"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        Prevalence:
        - PrevalenceGeographic: Worldwide
          PrevalenceType: Cases/families
          PrevalenceQualification: Case
          PrevalenceValidationStatus: Validated
          PrevalenceClass: None
          Source: 11389160[PMID]_9689990[PMID]_ [EXPERT]
          ValMoy: "4.0"
        - PrevalenceGeographic: Worldwide
          PrevalenceType: Cases/families
          PrevalenceQualification: Case
          PrevalenceValidationStatus: Validated
          PrevalenceClass: None
          Source: 11389160[PMID]_9689990[PMID]_ [EXPERT]
          ValMoy: "4.0"
        DisorderGroup: Disorder
        DisorderType: Disease
        Name: Multiple epiphyseal dysplasia, Al-Gazali type
    list_orphacode:
      type: array
      items:
        type: string
        example: '[''58'', ''558'']'
    list_hchid:
      type: array
      items:
        type: string
        example: '[''146'', ''233'']'
    list_symbol:
      type: array
      items:
        type: string
        example: '[''KIF7'']'
    product1_DisorderFlag:
      type: object
      properties:
        Label:
          type: string
          example: on-line
      example:
        Label: on-line
    product1_DisorderType:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "377789"
        Name:
          type: string
          example: Malformation syndrome
      example:
        ORPHAcode: "377789"
        Name: Malformation syndrome
    product1_DisorderMappingRelation:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "377807"
        Name:
          type: string
          example: E (exact mapping (the terms and the concepts are equivalent))
      example:
        ORPHAcode: "377807"
        Name: E (exact mapping (the terms and the concepts are equivalent))
    product1_DisorderMappingValidationStatus:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "377819"
        Name:
          type: string
          example: Validated
      example:
        ORPHAcode: "377819"
        Name: Validated
    product1_ExternalReference:
      type: object
      properties:
        Source:
          type: string
          example: MeSH
        Reference:
          type: string
          example: C537494
        DisorderMappingRelation:
          $ref: '#/components/schemas/product1_DisorderMappingRelation'
        DisorderMappingICDRelation:
          type: string
          example: None
        DisorderMappingValidationStatus:
          $ref: '#/components/schemas/product1_DisorderMappingValidationStatus'
      example:
        DisorderMappingICDRelation: None
        Reference: C537494
        DisorderMappingValidationStatus:
          ORPHAcode: "377819"
          Name: Validated
        Source: MeSH
        DisorderMappingRelation:
          ORPHAcode: "377807"
          Name: E (exact mapping (the terms and the concepts are equivalent))
    product1_Disorder2:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "3450"
        Name:
          type: string
          example: Weissenbacher-Zweymuller syndrome
      example:
        ORPHAcode: "3450"
        Name: Weissenbacher-Zweymuller syndrome
    product1_DisorderDisorderAssociation:
      type: object
      properties:
        Disorder1:
          type: string
          example: None
        Disorder2:
          $ref: '#/components/schemas/product1_Disorder2'
        DisorderDisorderAssociationType:
          type: string
          example: Moved to
      example:
        DisorderDisorderAssociationType: Moved to
        Disorder1: None
        Disorder2:
          ORPHAcode: "3450"
          Name: Weissenbacher-Zweymuller syndrome
    product1_TextualInformation:
      type: object
      properties:
        Definition:
          type: string
          example: Stickler syndrome type 3 is a rare, genetic, multiple congenital
            anomalies/dysmorphic syndrome characterized by craniofacial dysmorphism
            (midface hypoplasia, depressed nasal bridge, small nose with upturned
            tip, cleft palate, Pierre Robin sequence), bilateral, pronounced sensorineural
            hearing loss, and skeletal/joint anomalies (including spondyloepiphyseal
            dysplasia, arthralgia/arthropathy), in the absence of ocular abnormalities.
      example:
        Definition: Stickler syndrome type 3 is a rare, genetic, multiple congenital
          anomalies/dysmorphic syndrome characterized by craniofacial dysmorphism
          (midface hypoplasia, depressed nasal bridge, small nose with upturned tip,
          cleft palate, Pierre Robin sequence), bilateral, pronounced sensorineural
          hearing loss, and skeletal/joint anomalies (including spondyloepiphyseal
          dysplasia, arthralgia/arthropathy), in the absence of ocular abnormalities.
    product4_Disorder_HPO:
      type: object
      properties:
        HPOId:
          type: string
          example: HP:0000137
        HPOTerm:
          type: string
          example: Abnormality of the ovary
      example:
        HPOTerm: Abnormality of the ovary
        HPOId: HP:0000137
    product4_Disorder_HPODisorderAssociation:
      type: object
      properties:
        HPO:
          $ref: '#/components/schemas/product4_Disorder_HPO'
        HPOFrequency:
          type: string
          example: Very frequent (99-80%)
        DiagnosticCriteria:
          type: string
          example: None
      example:
        HPO:
          HPOTerm: Abnormality of the ovary
          HPOId: HP:0000137
        HPOFrequency: Very frequent (99-80%)
        DiagnosticCriteria: None
    product4_Disorder:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "881"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=881
        Name:
          type: string
          example: Turner syndrome
        DisorderType:
          type: string
          example: Malformation syndrome
        DisorderGroup:
          type: string
          example: Disorder
        HPODisorderAssociation:
          type: array
          items:
            $ref: '#/components/schemas/product4_Disorder_HPODisorderAssociation'
      example:
        ORPHAcode: "881"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=881
        DisorderGroup: Disorder
        HPODisorderAssociation:
        - HPO:
            HPOTerm: Abnormality of the ovary
            HPOId: HP:0000137
          HPOFrequency: Very frequent (99-80%)
          DiagnosticCriteria: None
        - HPO:
            HPOTerm: Abnormality of the ovary
            HPOId: HP:0000137
          HPOFrequency: Very frequent (99-80%)
          DiagnosticCriteria: None
        DisorderType: Malformation syndrome
        Name: Turner syndrome
    product6_Gene_ExternalReference:
      type: object
      properties:
        Source:
          type: string
          example: Ensembl
        Reference:
          type: string
          example: ENSG00000166813
      example:
        Reference: ENSG00000166813
        Source: Ensembl
    product6_Gene_Locus:
      type: object
      properties:
        GeneLocus:
          type: string
          example: 15q26.1
        LocusKey:
          type: string
          example: "1"
      example:
        GeneLocus: 15q26.1
        LocusKey: "1"
    product6_Gene:
      type: object
      properties:
        Name:
          type: string
          example: kinesin family member 7
        Symbol:
          type: string
          example: KIF7
        Synonym:
          type: array
          items:
            type: string
            example: '[''JBTS12'']'
        GeneType:
          type: string
          example: gene with protein product
        ExternalReference:
          type: array
          items:
            $ref: '#/components/schemas/product6_Gene_ExternalReference'
        Locus:
          type: array
          items:
            $ref: '#/components/schemas/product6_Gene_Locus'
      example:
        ExternalReference:
        - Reference: ENSG00000166813
          Source: Ensembl
        - Reference: ENSG00000166813
          Source: Ensembl
        Symbol: KIF7
        Synonym:
        - '[''JBTS12'']'
        - '[''JBTS12'']'
        GeneType: gene with protein product
        Locus:
        - GeneLocus: 15q26.1
          LocusKey: "1"
        - GeneLocus: 15q26.1
          LocusKey: "1"
        Name: kinesin family member 7
    product6_DisorderGeneAssociation:
      type: object
      properties:
        SourceOfValidation:
          type: string
          example: 22587682[PMID]
        Gene:
          $ref: '#/components/schemas/product6_Gene'
        DisorderGeneAssociationType:
          type: string
          example: Disease-causing germline mutation(s) in
        DisorderGeneAssociationStatus:
          type: string
          example: Assessed
      example:
        DisorderGeneAssociationStatus: Assessed
        Gene:
          ExternalReference:
          - Reference: ENSG00000166813
            Source: Ensembl
          - Reference: ENSG00000166813
            Source: Ensembl
          Symbol: KIF7
          Synonym:
          - '[''JBTS12'']'
          - '[''JBTS12'']'
          GeneType: gene with protein product
          Locus:
          - GeneLocus: 15q26.1
            LocusKey: "1"
          - GeneLocus: 15q26.1
            LocusKey: "1"
          Name: kinesin family member 7
        DisorderGeneAssociationType: Disease-causing germline mutation(s) in
        SourceOfValidation: 22587682[PMID]
    product6_gene_disorder:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "166024"
        ExpertLink:
          type: string
          example: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        Name:
          type: string
          example: Multiple epiphyseal dysplasia, Al-Gazali type
        DisorderType:
          type: string
          example: Disease
        DisorderGroup:
          type: string
          example: Disorder
      example:
        ORPHAcode: "166024"
        ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
        DisorderGroup: Disorder
        DisorderType: Disease
        Name: Multiple epiphyseal dysplasia, Al-Gazali type
    product6_gene_GeneDisorderAssociation:
      type: object
      properties:
        SourceOfValidation:
          type: string
          example: 22587682[PMID]
        DisorderGeneAssociationType:
          type: string
          example: Disease-causing germline mutation(s) in
        DisorderGeneAssociationStatus:
          type: string
          example: Assessed
        disorder:
          $ref: '#/components/schemas/product6_gene_disorder'
      example:
        DisorderGeneAssociationStatus: Assessed
        disorder:
          ORPHAcode: "166024"
          ExpertLink: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024
          DisorderGroup: Disorder
          DisorderType: Disease
          Name: Multiple epiphyseal dysplasia, Al-Gazali type
        DisorderGeneAssociationType: Disease-causing germline mutation(s) in
        SourceOfValidation: 22587682[PMID]
    product9_prev_Prevalence:
      type: object
      properties:
        Source:
          type: string
          example: 11389160[PMID]_9689990[PMID]_ [EXPERT]
        PrevalenceType:
          type: string
          example: Cases/families
        PrevalenceQualification:
          type: string
          example: Case
        PrevalenceClass:
          type: string
          example: None
        ValMoy:
          type: string
          example: "4.0"
        PrevalenceGeographic:
          type: string
          example: Worldwide
        PrevalenceValidationStatus:
          type: string
          example: Validated
      example:
        PrevalenceGeographic: Worldwide
        PrevalenceType: Cases/families
        PrevalenceQualification: Case
        PrevalenceValidationStatus: Validated
        PrevalenceClass: None
        Source: 11389160[PMID]_9689990[PMID]_ [EXPERT]
        ValMoy: "4.0"
  responses:
    "403":
      description: Access denied
    "404":
      description: Queried disorder not found
    default:
      description: Unknown internal error
  parameters:
    hchid:
      name: hchid
      in: path
      description: The hierarchy ID (hchID) is a number which refers to an Orphanet
        classification
      required: true
      style: simple
      explode: false
      schema:
        minimum: 0
        exclusiveMinimum: true
        type: integer
    language:
      name: language
      in: path
      description: Specify the language in the list supported by Orphanet (CS, DE,
        EN, ES, FR, IT, NL, PL, PT)
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: EN
        enum:
        - CS
        - DE
        - EN
        - ES
        - FR
        - IT
        - NL
        - PL
        - PT
    orphacode:
      name: orphacode
      in: path
      description: The ORPHAcode is a unique identifier to reference an Orphanet's
        concept
      required: true
      style: simple
      explode: false
      schema:
        minimum: 0
        exclusiveMinimum: true
        type: integer
        format: int32
    symbol:
      name: symbol
      in: path
      description: The symbol is an identifier to reference a gene
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    UserSecurity:
      type: apiKey
      name: SIMPLE-API-KEY
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_UserSecurity
    AdminSecurity:
      type: apiKey
      name: ADMIN-API-KEY
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_AdminSecurity

